# 1. Definindo a rede interna
networks:
  gdash_network:
    driver: bridge

# 2. Configurando os serviços
services:
  # 2.1 Serviço MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gdash_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # 2.2 Fila de Mensagens (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gdash_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  # 2.3 Collector Python (Coleta de dados)
  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    container_name: collector_container
    restart: unless-stopped
    environment:
      # RabbitMQ
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: rabbituser
      RABBITMQ_PASSWORD: rabbitpass
      RABBITMQ_QUEUE: weather_queue
      RABBITMQ_EXCHANGE: ""

      # API Open-Meteo
      API_URL: https://api.open-meteo.com/v1/forecast?latitude=-12.9714&longitude=-38.5014&current=temperature_2m,relative_humidity_2m,wind_speed_10m,weather_code
      API_TOKEN: ""
      API_TIMEOUT: 30

      # Collector Config
      COLLECTION_INTERVAL: 300
      MAX_RETRIES: 3
      RETRY_DELAY: 5

      # Logging
      LOG_LEVEL: INFO
      LOG_FILE: logs/collector.log
    volumes:
      - ./collector/logs:/app/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - gdash_network

  # 2.4 Serviço de API (Nest.JS)
  api_service:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_gdash
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://rootuser:rootpass@mongodb:27017/gdash?authSource=admin
      RABBITMQ_URI: amqp://rabbituser:rabbitpass@rabbitmq:5672
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - gdash_network

# 3. Configuração de Volumes
volumes:
  mongo_data:
  rabbitmq_data:
